spring.application.name=booking-microservice

spring.jpa.hibernate.ddl-auto=update
server.port=8080

# Configuración de la base de datos
spring.datasource.username=bookingJC
spring.datasource.url=jdbc:postgresql://localhost:5432/bookingJC
spring.datasource.password=1234

# Configuración de Eureka
eureka.client.service-url.defaultZone=http://localhost:8787/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


