spring.application.name=flights-microservice

server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/flights_db
spring.datasource.username = postgres_user
spring.datasource.password = 1234
#spring.datasource.db =

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.generate-ddl=true

# Configuración de Eureka
eureka.client.service-url.defaultZone=http://localhost:8787/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


