spring.application.name=api-gateway

# Puerto donde corre el API Gateway
server.port=9999

# Configurar el servidor Eureka (Discovery Service)
eureka.client.service-url.defaultZone=http://localhost:8787/eureka/

eureka.client.register-with-eureka=false

eureka.client.fetch-registry=false

# Configurar el ID de la instancia de Eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# Habilitar el balanceador de carga
spring.cloud.loadbalancer.enabled=true

# Habilitar la localización automática de servicios en Eureka
spring.cloud.gateway.discovery.locator.enabled=true

# Definición de las rutas manuales
spring.cloud.gateway.routes[0].id=BookingMicroserviceApplication
spring.cloud.gateway.routes[0].uri=lb://BOOKING
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/bookings/**
